version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: remotejobs-db
    environment:
      POSTGRES_DB: remotejobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  app:
#    build: .
#    container_name: remotejobs-app
#    depends_on:
#      postgres:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#    environment:
#      DB_USERNAME: postgres
#      DB_PASSWORD: postgres
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5430/remotejobs
#    restart: unless-stopped

volumes:
  pgdata: